server {
    listen 80;
    server_name platform-skadi.ru;

    # location for getting SSL certificate from Let's Encrypt
    location /.well-known/ {
        root /var/www/certbot;
    }

    # redirect from http to https
    location / {
        return 301 https://$host$request_uri;
    }
}
