user nginx;
worker_processes auto;
pid        /var/run/nginx.pid;

events {
    worker_connections 2048;
    multi_accept on;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main  '$remote_addr - - [$time_local] {$status} (ResponseTime $upstream_response_time) "$http_referer": '
                     '"$request" (Bytes $body_bytes_sent) "$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;
    error_log   /var/log/nginx/error.log notice;

    sendfile on;
    aio      on;
    # disable nginx version headers like "Server: nginx/1.20.2"
    server_tokens off;
    # define keep-alive connection timeout (sec)
    keepalive_timeout 90;
	# define max request count in keep-alive connection
    keepalive_requests 150;

    # send the client a "request timed out" if the body is not loaded by this time (sec)
    client_body_timeout 30;
    # if the client stops reading data, free up the stale client connection after this much time (sec)
    send_timeout 15;

    # compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_min_length 1024;  # 1Kb (in bytes)
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml+rss
        application/rss+xml
        application/atom+xml
        image/svg+xml
        text/x-js
        application/x-font-ttf
        application/x-font-opentype
        application/vnd.ms-fontobject

    # DDOS-guard
    limit_req_zone $binary_remote_addr zone=ddos:10m rate=10r/s;

    include /etc/nginx/conf.d/http_site.conf;
    #include /etc/nginx/conf.d/https_site.conf;
}
