DROP TABLE IF EXISTS class;

CREATE TABLE IF NOT EXISTS class (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    teacher_id BIGINT NULL,
    schedule VARCHAR(100) NULL
);

ALTER TABLE class
ADD CONSTRAINT class_teacher_fk FOREIGN KEY (teacher_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE user ADD COLUMN class_id BIGINT NULL;

ALTER TABLE user
ADD CONSTRAINT student_class_fk FOREIGN KEY (class_id) REFERENCES class (id) ON UPDATE CASCADE ON DELETE SET NULL;